filebeat.config:
  prospectors:
    path: /usr/share/filebeat/prospectors.d/*.yml
    reload.enabled: false
  modules:
    path: /usr/share/filebeat/modules.d/*.yml
    reload.enabled: false

processors:
- add_cloud_metadata:

output.logstash:
  hosts: ["192.168.99.100:5000"]
